# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               CloudSuite
tagline:             'The Suite of Scale-out Benchmarks'
description:         'CloudSuite'
url:                 http://cloudsuite.ch
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              CloudSuite
  url:               https://cloudsuite.ch
  email:             cloudsuite@listes.epfl.ch

# Custom vars
version:             1.0.0

exclude: 			 [old]
